### ISSUE TITLE
Parse general election precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-mi#1]
The state produces tab-delimited text files for general elections since 1998. These are contained in zip files that can be found [here](http://miboecfr.nictusa.com/cgi-bin/cfr/precinct_srch.cgi). The layout for the files is in the readme.txt in each zip file. What's needed is a script that would take a general election's zip file and generate a CSV file from the component files inside the zip file.

The names of the CSV files should have the following format: `yymmdd__mi__general__precinct.csv`

We're interested in results for all federal and state offices, but if you want to generate files for the entire file, that's fine.

And the CSV files should have at least these fields: `county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

Include a precinct total for each candidate and also the precinct marked "statistical adjustment," which is the difference between the official canvass results and the precinct results.

- [x] 2016 general
- [x] 2014 general
- [x] 2012 general
- [x] 2010 general
- [x] 2008 general
- [x] 2006 general
- [x] 2004 general
- [x] 2002 general
- [x] 2000 general

**Comment by lawsonbh** [comment]
Ostrich chiming in: I will take responsibility for this. We are in the middle of move, so my responses will be delayed. Once I start getting into the files, I will draft up a timeline.

**Comment by lephead** [comment]
No, the statistical adjustment is also the difference between the official canvass results and the precinct results.

**Comment by dwillis** [comment]
@lawsonbh are you still interested/able to do this? if not, that's fine - I can give it to someone else.

**Comment by lawsonbh** [comment]
Hi Derek – I am sorry - I have been trying to work with Tabula, but it’s a little outside of my normal experience ( which is good for growth! ). Should have contacted you earlier. Please assign this to someone else who can work more quickly. 

Sent from Mail for Windows 10

**Comment by dwillis** [comment]
@lawsonbh That's no problem at all. Thanks for replying so quickly!

**Comment by dantonnoriega** [comment]
made a pull request to update the ["source" branch for MI](https://github.com/dantonnoriega/openelections-sources-mi). Now contains raw text data from 1998 onward for all counties.

I'll work on scripting and converting the files tomorrow. dusting off the old python skills was fun!

**Comment by dwillis** [comment]
@dantonnoriega awesome, thank you!
