### ISSUE TITLE
2022 duplicated/nearly duplicated precincts

### ISSUE THREAD

**Issue by sbaltzmit** [openelections/openelections-data-mi#59]
Hi! Thanks so much as always for collecting this excellent and badly needed data. I was wondering if anyone has thoughts about the origins of some precincts with the same name and different vote totals. An example is the precinct value `The Village of Grosse Pointe\nShores, A Michigan City,` (note that there's a line break character between `Pointe` and `Shores`) which reports different vote totals for candidates. There are on the order of ten thousand rows which have the same geographic information (precinct + county) as some other row, but they're not concentrated in any one one county or office, so I'm guessing that either disambiguating information was not available or wasn't captured in the original raw data. All of these precincts are real and I believe the vote totals are correct, they just don't have distinguishing names. I'm more than happy to poke around at some of the relevant code if anyone has a suggestion for where to start. Thanks!

**Comment by dwillis** [comment]
@sbaltzmit thanks for this report - we've replaced both the Wayne file and the statewide precinct file.
