### ISSUE TITLE
2022 General Clinton County Results - missing State Senate

### ISSUE THREAD

**Issue by claytonperry** [openelections/openelections-data-mi#61]
Hello!

Writing to flag that in the overall 2022 results file and in the Clinton county results file, the State Senate results (Districts 28 and 34) appear to be missing. I can see them in the canvass PDF file but they do not appear to have made it over to the CSVs.

I'll see if I can parse them myself; I'm not a proficient Python programmer but will take a whirl at it and see if I can correct this myself - appreciate all your hard work on this project!

**Comment by dwillis** [comment]
@claytonperry thanks! let me know if you don't have any luck parsing them and we'll get them added.

**Comment by claytonperry** [comment]
Thanks, @dwillis! If it's alright, I'd love use this issue to name a couple other inconsistencies in the state senate results, just so I can keep track of them:

- State Senate results in Crawford county have District = 35, but Crawford only falls within District 36; probably just need to replace
- Democratic Votes for State Senator District 36 in Arenac County are off by 100; probably a misparse of a precinct vote total
- Democratic Votes for State Senator District 16 in Monroe county are off by 1000; this is a misparse of the vote total in precinct Frenchtown Township, Precinct 3 (reads 1,266, should be 266)
- Republican Votes for State Senator District 16 in Monroe county are off by 344; this is a misparse of the vote total in precinct City of Luna Pier, Precinct 1 (reads 688, should be 344)
- Votes for Dem and Rep in Mackinac county for State Senator Districts 37 and 38 appear to be double the correct value - this is due to inclusion of County Totals rows (Precinct name: "Mackinac County Michigan - Total")
- State Senate results in Keneenaw county are missing District value (should be 38)
- Van Buren county records include results with office = "State Senate" and district = 38; this county is not in that district, probably meant to be office = "State House" (does fall within SH District 38). Relatedly, this county's records also include results with office = "State Senate" and district = 39, which does not exist - but also is probably meant to be office = "State House"

**Comment by dwillis** [comment]
@claytonperry thanks very much - we'll get on those fixes.

**Comment by dwillis** [comment]
@claytonperry fixed these issues; the fun part about the Crawford County issue is that the results mistakenly say District 35:
<img width="218" alt="Screenshot 2023-08-23 at 8 18 41 PM" src="https://github.com/openelections/openelections-data-mi/assets/2214/89e19101-2492-48b7-a996-79aeb21b05f6">

**Comment by claytonperry** [comment]
thanks so much for making those fixes, @dwillis ! it's a huge help!

**Comment by dwillis** [comment]
@claytonperry thanks for pointing them out - i need to regenerate the statewide file and will do that asap.
