### ISSUE TITLE
Any prospects of pulling togetherthe results from "Proposal 3, Right to Reproductive Freedom Initiative (2022)"?

### ISSUE THREAD

**Issue by jonrobinson2** [openelections/openelections-data-mi#62]
Noticed in the main file that you all just pulled partisan races. Is it possible to get the initiative results without much lift from what you've already done? Imagine people are interested.

**Comment by dwillis** [comment]
@jonrobinson2 It's possible, but not super simple. Let me see what we can do.

**Comment by jonrobinson2** [comment]
I figured that might be the case! Thanks for looking into it.
