### ISSUE TITLE
2022 Candidate/Party Mixed Up

### ISSUE THREAD

**Issue by mcastillon** [openelections/openelections-data-mi#63]
There are many examples in the [2022 data](https://github.com/openelections/openelections-data-mi/blob/master/2022/20221108__mi__general__precinct.csv) where the Candidate and Party are mixed up. For example, row 198 has _DEM_ in the `candidate` column, and _Gretchen Whitmer_ in the `party` column. The problem appears to be isolated to Tuscola and Montmorency counties. Is this a known issue?

**Comment by dwillis** [comment]
@mcastillon Will fix, thanks!

**Comment by dwillis** [comment]
Should be fixed now!
